from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import run_input_logic_tests as runner


runner.TESTS = [
    # 条件推理 / Conditional logic
    {
        "id": "C01_wason_basic",
        "kind": "conditional_logic",
        "prompt": "C01 Answer only card labels Cards A D 4 7 Rule If vowel then even Which cards must be turned",
        "zh_question": "卡片 A、D、4、7。规则：如果一面是元音，另一面是偶数。必须翻哪几张？",
        "expected": ["A and 7", "A, 7", "A 7", "7 and A"],
    },
    {
        "id": "C02_affirming_consequent",
        "kind": "conditional_logic",
        "prompt": "C02 Answer only yes or no If it rains the ground is wet The ground is wet Does it follow that it rained",
        "zh_question": "如果下雨，地面会湿。现在地面湿了。是否必然推出下雨了？",
        "expected": ["no"],
    },
    {
        "id": "C03_modus_tollens",
        "kind": "conditional_logic",
        "prompt": "C03 Answer only yes or no If machine works light turns green Light is not green Does it follow machine does not work",
        "zh_question": "如果机器正常，灯会变绿。灯没有变绿。是否推出机器不正常？",
        "expected": ["yes"],
    },
    {
        "id": "C04_denying_antecedent",
        "kind": "conditional_logic",
        "prompt": "C04 Answer only yes or no If a number is divisible by 4 it is even This number is not divisible by 4 Does it follow it is not even",
        "zh_question": "如果一个数能被 4 整除，它就是偶数。某数不能被 4 整除。是否推出它不是偶数？",
        "expected": ["no"],
    },
    {
        "id": "C05_contrapositive",
        "kind": "conditional_logic",
        "prompt": "C05 Answer only equivalent or not equivalent Statement If P then Q Compare If not Q then not P",
        "zh_question": "命题“如果 P 则 Q”和“如果非 Q 则非 P”是否等价？",
        "expected": ["equivalent"],
    },
    {
        "id": "C06_inverse",
        "kind": "conditional_logic",
        "prompt": "C06 Answer only equivalent or not equivalent Statement If P then Q Compare If not P then not Q",
        "zh_question": "命题“如果 P 则 Q”和“如果非 P 则非 Q”是否等价？",
        "expected": ["not equivalent"],
    },
    {
        "id": "C07_chain",
        "kind": "conditional_logic",
        "prompt": "C07 Answer only yes or no If A then B If B then C A is true Does C follow",
        "zh_question": "如果 A 则 B；如果 B 则 C；A 为真。是否推出 C？",
        "expected": ["yes"],
    },
    {
        "id": "C08_or_condition",
        "kind": "conditional_logic",
        "prompt": "C08 Answer only yes or no If A or B then C C is false Does it follow A is false and B is false",
        "zh_question": "如果 A 或 B 成立，则 C 成立。C 为假。是否推出 A 和 B 都为假？",
        "expected": ["yes"],
    },
    {
        "id": "C09_unless",
        "kind": "conditional_logic",
        "prompt": "C09 Answer only yes or no Unless the key is valid the door stays locked Door is unlocked Does it follow key is valid",
        "zh_question": "除非钥匙有效，否则门会锁着。现在门没锁。是否推出钥匙有效？",
        "expected": ["yes"],
    },
    {
        "id": "C10_sufficient_not_necessary",
        "kind": "conditional_logic",
        "prompt": "C10 Answer only yes or no Passing final exam is sufficient to pass course Lee passed course Does it follow Lee passed final exam",
        "zh_question": "通过期末考试足以通过课程。Lee 通过了课程。是否推出 Lee 通过了期末考试？",
        "expected": ["no"],
    },
    # 概率与认知偏差 / Probability and bias
    {
        "id": "P01_linda",
        "kind": "probability_bias",
        "prompt": "P01 Answer only bank teller or bank teller and feminist Linda studied philosophy Which is more likely bank teller or bank teller and feminist",
        "zh_question": "琳达学过哲学。哪个更可能：银行出纳，还是银行出纳且是女权主义者？",
        "expected": ["bank teller"],
        "reject": ["and feminist"],
    },
    {
        "id": "P02_monty",
        "kind": "probability_bias",
        "prompt": "P02 Answer only switch or stay Three door game you pick one host opens goat door Should you switch",
        "zh_question": "三门问题：你选一扇门，主持人打开一扇有羊的门。要提高中奖率应换门还是坚持？",
        "expected": ["switch"],
    },
    {
        "id": "P03_base_rate",
        "kind": "probability_bias",
        "prompt": "P03 Answer only more likely engineer or lawyer Town has 990 lawyers 10 engineers Person likes math Which profession more likely without stronger evidence",
        "zh_question": "镇上有 990 个律师、10 个工程师。某人喜欢数学。没有更强证据时哪个职业更可能？",
        "expected": ["lawyer"],
    },
    {
        "id": "P04_bayes_medical",
        "kind": "probability_bias",
        "prompt": "P04 Answer only low or high Disease prevalence is 1 percent Test positive rate is 99 percent if sick and 5 percent if healthy Is probability sick after positive low or high",
        "zh_question": "疾病患病率 1%，病人阳性率 99%，健康者误阳性 5%。阳性后患病概率是低还是高？",
        "expected": ["low"],
    },
    {
        "id": "P05_gambler",
        "kind": "probability_bias",
        "prompt": "P05 Answer only yes or no A fair coin landed heads five times Is tails more likely next toss",
        "zh_question": "公平硬币连续 5 次正面。下一次反面是否更可能？",
        "expected": ["no"],
    },
    {
        "id": "P06_sample_size",
        "kind": "probability_bias",
        "prompt": "P06 Answer only small or large Which hospital is more likely to have a day with over 60 percent boys born small hospital or large hospital",
        "zh_question": "哪种医院更容易某天男婴比例超过 60%：小医院还是大医院？",
        "expected": ["small"],
    },
    {
        "id": "P07_regression",
        "kind": "probability_bias",
        "prompt": "P07 Answer only yes or no After an unusually high score is the next score likely closer to average even without intervention",
        "zh_question": "一次异常高分之后，即使没有干预，下一次分数是否通常更接近平均值？",
        "expected": ["yes"],
    },
    {
        "id": "P08_sunk_cost",
        "kind": "probability_bias",
        "prompt": "P08 Answer only yes or no You paid for a bad movie Should the paid cost alone make you keep watching",
        "zh_question": "你已经花钱买了很差的电影票。仅仅因为已经付钱，是否应该继续看？",
        "expected": ["no"],
    },
    {
        "id": "P09_independence",
        "kind": "probability_bias",
        "prompt": "P09 Answer only same or different Roll a fair die It showed six twice Is probability of six next roll same or different",
        "zh_question": "公平骰子连续两次掷出 6。下一次掷出 6 的概率是相同还是不同？",
        "expected": ["same"],
    },
    {
        "id": "P10_conjunction",
        "kind": "probability_bias",
        "prompt": "P10 Answer only A or A and B Which is always at least as likely event A or event A and B",
        "zh_question": "哪个概率总是不小于另一个：事件 A，还是事件 A 且 B？",
        "expected": ["A"],
        "reject": ["A and B"],
    },
    # 真话假话 / Knights and knaves
    {
        "id": "T01_both_knaves",
        "kind": "truth_liar_logic",
        "prompt": "T01 Answer only A status and B status Knights tell truth knaves lie A says we are both knaves What are A and B",
        "zh_question": "骑士说真话，骗子说假话。A 说：我们俩都是骗子。A 和 B 是什么？",
        "expected": ["A is knave, B is knight", "A knave B knight"],
    },
    {
        "id": "T02_same_type",
        "kind": "truth_liar_logic",
        "prompt": "T02 Answer only same or different A says B is a knight B says A is a knave Are A and B same type or different type",
        "zh_question": "A 说 B 是骑士；B 说 A 是骗子。A 和 B 是同类还是不同类？",
        "expected": ["different"],
    },
    {
        "id": "T03_one_truth",
        "kind": "truth_liar_logic",
        "prompt": "T03 Answer only A or B or C Exactly one tells truth A says B lies B says C lies C says A lies Who tells truth",
        "zh_question": "三人恰好一人说真话。A 说 B 说谎；B 说 C 说谎；C 说 A 说谎。谁说真话？",
        "expected": ["A", "B", "C"],
    },
    {
        "id": "T04_two_truth",
        "kind": "truth_liar_logic",
        "prompt": "T04 Answer only names Exactly two statements are true A says B is guilty B says C is guilty C says B is lying Which statements are true",
        "zh_question": "恰好两句话为真：A 说 B 有罪；B 说 C 有罪；C 说 B 在说谎。哪些人的话为真？",
        "expected": ["A and C", "C and A", "A, C"],
    },
    {
        "id": "T05_guilty",
        "kind": "truth_liar_logic",
        "prompt": "T05 Answer only guilty person Exactly one statement true A says B guilty B says A not guilty C says B not guilty Exactly one guilty Who guilty",
        "zh_question": "恰好一句真话：A 说 B 有罪；B 说 A 无罪；C 说 B 无罪。恰好一人有罪。谁有罪？",
        "expected": ["A"],
    },
    {
        "id": "T06_all_liars_claim",
        "kind": "truth_liar_logic",
        "prompt": "T06 Answer only possible or impossible A says all three of us are liars In knights knaves setting Is this possible",
        "zh_question": "A 说：我们三个人全是骗子。在骑士/骗子设定下这是否可能？",
        "expected": ["impossible"],
    },
    {
        "id": "T07_exactly_one_knight",
        "kind": "truth_liar_logic",
        "prompt": "T07 Answer only knight name A says exactly one of us is knight B says A is knave C says B is knave Who is knight",
        "zh_question": "A 说：我们中恰好一个是骑士。B 说 A 是骗子。C 说 B 是骗子。谁是骑士？",
        "expected": ["C"],
    },
    {
        "id": "T08_two_doors",
        "kind": "truth_liar_logic",
        "prompt": "T08 Answer only opposite door One guard lies one tells truth Ask which door would other guard say is safe Choose what door",
        "zh_question": "一真一假两个守卫。问任一守卫：另一个会说哪扇门安全？你应选择哪扇门？",
        "expected": ["opposite"],
    },
    {
        "id": "T09_mutual_accuse",
        "kind": "truth_liar_logic",
        "prompt": "T09 Answer only one knight or one knave A says B is knave B says A is knave What must be true",
        "zh_question": "A 说 B 是骗子；B 说 A 是骗子。必然是什么情况？",
        "expected": ["one knight", "one knave"],
    },
    {
        "id": "T10_double_claim",
        "kind": "truth_liar_logic",
        "prompt": "T10 Answer only A status A says I am a knave Is A knight or knave or impossible",
        "zh_question": "A 说：我是骗子。A 是骑士、骗子，还是这种情况不可能？",
        "expected": ["impossible"],
    },
    # 量词与形式逻辑 / Quantifiers
    {
        "id": "Q01_some_chain",
        "kind": "quantifier_logic",
        "prompt": "Q01 Answer only yes or no All poets are writers Some artists are poets Does some artists are writers follow",
        "zh_question": "所有诗人都是作家；有些艺术家是诗人。是否推出有些艺术家是作家？",
        "expected": ["yes"],
    },
    {
        "id": "Q02_invalid_convert",
        "kind": "quantifier_logic",
        "prompt": "Q02 Answer only yes or no All cats are mammals Does all mammals are cats follow",
        "zh_question": "所有猫都是哺乳动物。是否推出所有哺乳动物都是猫？",
        "expected": ["no"],
    },
    {
        "id": "Q03_neg_every",
        "kind": "quantifier_logic",
        "prompt": "Q03 Answer only correct negation The negation of every report has an error is some report has no error or no report has error",
        "zh_question": "“每份报告都有错误”的正确否定是“有些报告没有错误”还是“没有报告有错误”？",
        "expected": ["some report has no error"],
    },
    {
        "id": "Q04_none_some",
        "kind": "quantifier_logic",
        "prompt": "Q04 Answer only yes or no No reptiles are warm blooded Some pets are reptiles Does some pets are not warm blooded follow",
        "zh_question": "没有爬行动物是温血的；有些宠物是爬行动物。是否推出有些宠物不是温血的？",
        "expected": ["yes"],
    },
    {
        "id": "Q05_some_not",
        "kind": "quantifier_logic",
        "prompt": "Q05 Answer only yes or no Some students are not athletes Does it follow some athletes are not students",
        "zh_question": "有些学生不是运动员。是否推出有些运动员不是学生？",
        "expected": ["no"],
    },
    {
        "id": "Q06_all_not",
        "kind": "quantifier_logic",
        "prompt": "Q06 Answer only yes or no All A are B No B are C Does no A are C follow",
        "zh_question": "所有 A 都是 B；没有 B 是 C。是否推出没有 A 是 C？",
        "expected": ["yes"],
    },
    {
        "id": "Q07_some_overlap",
        "kind": "quantifier_logic",
        "prompt": "Q07 Answer only yes or no Some A are B Some B are C Does some A are C follow",
        "zh_question": "有些 A 是 B；有些 B 是 C。是否推出有些 A 是 C？",
        "expected": ["no"],
    },
    {
        "id": "Q08_only_if",
        "kind": "quantifier_logic",
        "prompt": "Q08 Answer only yes or no You can enter only if you have badge Sam entered Does Sam have badge follow",
        "zh_question": "只有有工牌才能进入。Sam 进入了。是否推出 Sam 有工牌？",
        "expected": ["yes"],
    },
    {
        "id": "Q09_if_and_only_if",
        "kind": "quantifier_logic",
        "prompt": "Q09 Answer only yes or no A if and only if B A is false Does B false follow",
        "zh_question": "A 当且仅当 B。A 为假。是否推出 B 为假？",
        "expected": ["yes"],
    },
    {
        "id": "Q10_exists_negation",
        "kind": "quantifier_logic",
        "prompt": "Q10 Answer only correct negation The negation of some files are encrypted is no files are encrypted or all files are encrypted",
        "zh_question": "“有些文件被加密”的否定是“没有文件被加密”还是“所有文件都被加密”？",
        "expected": ["no files are encrypted"],
    },
    # 反事实/排除推理 / Counterfactual and elimination
    {
        "id": "E01_three_boxes",
        "kind": "elimination_logic",
        "prompt": "E01 Answer only box Gold is in one box Labels red says gold in blue blue says gold not in blue green says gold in red Exactly one label true",
        "zh_question": "金子在一个盒子里。红盒标签说金子在蓝盒；蓝盒标签说金子不在蓝盒；绿盒标签说金子在红盒。恰好一个标签为真。金子在哪？",
        "expected": ["blue"],
    },
    {
        "id": "E02_hat",
        "kind": "elimination_logic",
        "prompt": "E02 Answer only color Three hats red blue green Person sees red and blue on others and knows not green What color is own hat",
        "zh_question": "三顶帽子红蓝绿。某人看到别人戴红和蓝，并知道自己不是绿。自己帽子是什么颜色？",
        "expected": ["green"],
    },
    {
        "id": "E03_zebra_small",
        "kind": "elimination_logic",
        "prompt": "E03 Answer only person Alice Bob Cara live in red blue green houses Alice not red Bob not blue Cara not green Alice lives blue Who lives red",
        "zh_question": "Alice、Bob、Cara 住红蓝绿三屋。Alice 不住红，Bob 不住蓝，Cara 不住绿，Alice 住蓝。谁住红屋？",
        "expected": ["Cara"],
    },
    {
        "id": "E04_order",
        "kind": "elimination_logic",
        "prompt": "E04 Answer only name Anna is before Ben Cara is after Ben Dan is before Anna Who is third",
        "zh_question": "Anna 在 Ben 前；Cara 在 Ben 后；Dan 在 Anna 前。谁排第三？",
        "expected": ["Ben"],
    },
    {
        "id": "E05_family",
        "kind": "elimination_logic",
        "prompt": "E05 Answer only relation Ana is Ben mother Ben is Cara father What is Ana to Cara",
        "zh_question": "Ana 是 Ben 的母亲，Ben 是 Cara 的父亲。Ana 是 Cara 的什么人？",
        "expected": ["grandmother", "grandma"],
    },
    {
        "id": "E06_hidden_truth",
        "kind": "elimination_logic",
        "prompt": "E06 Answer only yes or no If the safe is open then either code was used or key was used Safe is open Code was not used Does key was used follow",
        "zh_question": "如果保险箱打开，则要么用了密码，要么用了钥匙。保险箱打开了，且没用密码。是否推出用了钥匙？",
        "expected": ["yes"],
    },
    {
        "id": "E07_xor",
        "kind": "elimination_logic",
        "prompt": "E07 Answer only yes or no Exactly one of A and B is true A is false Does B true follow",
        "zh_question": "A 和 B 恰好一个为真。A 为假。是否推出 B 为真？",
        "expected": ["yes"],
    },
    {
        "id": "E08_not_both",
        "kind": "elimination_logic",
        "prompt": "E08 Answer only yes or no Not both A and B are true A is true Does B false follow",
        "zh_question": "A 和 B 不能同时为真。A 为真。是否推出 B 为假？",
        "expected": ["yes"],
    },
    {
        "id": "E09_minimal_change",
        "kind": "elimination_logic",
        "prompt": "E09 Answer only yes or no If changing one premise makes conclusion false was original argument deductively valid",
        "zh_question": "如果只改动一个前提就能让结论为假，是否说明原论证必然有效？",
        "expected": ["no"],
    },
    {
        "id": "E10_counterexample",
        "kind": "elimination_logic",
        "prompt": "E10 Answer only yes or no To disprove all swans are white is one black swan enough",
        "zh_question": "要反驳“所有天鹅都是白的”，一只黑天鹅是否足够？",
        "expected": ["yes"],
    },
]


if __name__ == "__main__":
    raise SystemExit(runner.main())
